### ISSUE TITLE
Create a Navigation Bar (Dashboard) like in the figure

### ISSUE THREAD

**Issue by dpakprajul** [dpakprajul/HouseManagementSystem#1]
![Capture](https://user-images.githubusercontent.com/38970123/153715022-0dacb26f-251d-4df2-b4bb-f5cd0496fc1b.JPG)

**Comment by dpakprajul** [comment]
Step 1) Use Bootstrap to make similar kind of dashboard

**Comment by bidurparajuli** [comment]
this has been completed except the content part.
