### ISSUE TITLE
create a good form using a lower bootstrap 

### ISSUE THREAD

**Issue by dpakprajul** [dpakprajul/HouseManagementSystem#6]
Don't use bootstrap 5.0 version. Use 4.0 version and it will solve the problem:
Also put all the forms inside a div with a class "main" as: <div class="main">  ..... </div>
add stylesheet reference in html first.  <link rel="stylesheet" href="style.css">
then in style.css file, change the padding of the main by : **.main{padding: 200px}**
![Capture](https://user-images.githubusercontent.com/38970123/153924540-cc0b3a24-a002-446c-8982-811703f14fad.JPG)
![image](https://user-images.githubusercontent.com/38970123/153924622-14e61843-c528-4b48-afa0-50297dbcd2fd.png)

**Comment by dpakprajul** [comment]
![image](https://user-images.githubusercontent.com/38970123/153937620-cd481c21-7ab5-4a8d-89c5-4965bd6b9b67.png)

also see this, how is it possible (in code compare): dark mode

**Comment by bidurparajuli** [comment]
![image](https://user-images.githubusercontent.com/15170184/154002131-9330d38b-7f09-447f-9933-a2f50d1456b1.png)


I changed the background to black but as you can see could not find where to change the color for the font to white.

**Comment by bidurparajuli** [comment]
Ill try again in a while

**Comment by bidurparajuli** [comment]
![image](https://user-images.githubusercontent.com/15170184/154004481-17243bf4-6511-42c1-a120-d81050844850.png)
yesko chorera mero yesto chai bhayo. Tero jasto ramro chai bhayena
![image](https://user-images.githubusercontent.com/15170184/154004631-e837ddf3-2853-449b-99cc-2bfde6db160c.png)

**Comment by bidurparajuli** [comment]
but i used the boootstrap stylesheet for dark mode. Could not do it from the code
